### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by sarah872** [nthomasCUBE/KEGGexpressionmapper#1]
I am running into errors when executing the following commands:

```
library(KEGGexpressionMapper)
KEGGexpressionMapper()
```

see my errorfile attached.
[error.txt](https://github.com/nthomasCUBE/KEGGexpressionmapper/files/1657234/error.txt)

**Comment by nthomasCUBE** [comment]
Hi Sarah,
many thanks for the error message, I will try to take a look into it the next days

br
thomas

**Comment by nthomasCUBE** [comment]
Hi Sarah,
i suppose, this is because of the length of the URL as the error tells, I changed the length of the
URL to 10 instead of 100, should run now for the linux version.
I will try next days to make it also run under windows
maybe you can use the current version where I changed the parameter in get_url.R from 100 to 10

br
thomas

**Comment by sarah872** [comment]
Thanks for getting back to this!

Unfortunately, still some errors are showing up:
I was again running

`library(KEGGexpressionMapper)
KEGGexpressionMapper(gene_desc = "Use_case2/DEG.tab", gene_kegg = "Use_case2/KEGG.tab", gene_expr = "Use_case2/EXPRESSION.tab", is_timeseries = FALSE, excel = NA)`

and got the error messages I attached.

[error_28Jan.txt](https://github.com/nthomasCUBE/KEGGexpressionmapper/files/1671206/error_28Jan.txt)

**Comment by nthomasCUBE** [comment]
Hi Sarah,

tried to integrate the changes in a new Version 0.2, should work now.
However, would like to make more changes in the next weeks.
Can also add more features if needded

br
