### ISSUE TITLE
black boxes

### ISSUE THREAD

**Issue by sarah872** [nthomasCUBE/KEGGexpressionmapper#2]
I have RNA-seq data of two conditions in triplicates each. Therefore, as an input, I have two conditions and the respective average of the triplicate.
Is it therefore normal that only black boxes (instead of colored ones) are drawn?

**Comment by nthomasCUBE** [comment]
Hi Sarah,
can you send me some lines of the input then I try to update the scripts

br
thomas

**Comment by sarah872** [comment]
Thanks for getting back to me!

DEG.tab

    gene
    gene_v1_1570005
    gene_v1_1950002
    gene_v1_1680004
    gene_v1_360012
    gene_v1_1650005
    gene_v1_730020
    gene_v1_660004
    gene_v1_1770003
    gene_v1_240017

KEGG.tab

    gene	KEGG_id
    gene_v1_1570005	K00370
    gene_v1_1950002	K03582
    gene_v1_1680004	K01873
    gene_v1_360012	K02335
    gene_v1_1650005	K01338
    gene_v1_730020	K16886
    gene_v1_660004	K04084
    gene_v1_1770003	K00394
    gene_v1_240017	K03798

Expression.tab

    id	condA	condB
    gene_v1_1570009	10.4	7.34
    gene_v1_1110020	10.53032826	7.57331342
    gene_v1_1730006	10.22436427	6.677510602
    gene_v1_710020	10.18394938	7.883923316
    gene_v1_1840001	10.18646509	8.060574857
    gene_v1_110046	10.36330263	8.008153526
    gene_v1_340011	10.4182013	8.195792844
    gene_v1_1690007	10.35297072	8.230811479
    gene_v1_190040	10.434968	8.329690923

**Comment by nthomasCUBE** [comment]
Hi Sarah,

i rewrote parts, but would like to make more changes and improve the tool over the next weeks, 

https://github.com/nthomasCUBE/KEGGexpressionmapper/releases/tag/v0.3

best

**Comment by sarah872** [comment]
thank you. Unfortunately, I still get black boxes. I imagined something like one color when it is upregulated in condA vs. condB, another color when it is downregulated.

**Comment by nthomasCUBE** [comment]
maybe because I added expression for the DEGs.. that you provided..
then it worked with version 0.3
but will check again next days 
best

DEG.tab
gene
gene_v1_1570005
gene_v1_1950002
gene_v1_1680004
gene_v1_360012
gene_v1_1650005
gene_v1_730020
gene_v1_660004
gene_v1_1770003
gene_v1_240017

Expression.tab
id	condA	condB
gene_v1_1570009	2.4	7.34
gene_v1_1110020	10.53032826	7.57331342
gene_v1_1730006	10.22436427	6.677510602
gene_v1_710020	1.18394938	7.883923316
gene_v1_1840001	10.18646509	3.060574857
gene_v1_110046	10.36330263	8.008153526
gene_v1_340011	5.4182013	4.195792844
gene_v1_1690007	10.35297072	8.230811479
gene_v1_190040	10.434968	8.329690923
gene_v1_1570005	1	2
gene_v1_1950002	3	4
gene_v1_1680004	5	5
gene_v1_360012	3	4
gene_v1_1650005	3	4
gene_v1_730020	4	4
gene_v1_660004	52	22
gene_v1_1770003	3	33
gene_v1_240017	3	33


KEGG.tab
gene	KEGG_id
gene_v1_1570005	K00370
gene_v1_1950002	K03582
gene_v1_1680004	K01873
gene_v1_360012	K02335
gene_v1_1650005	K01338
gene_v1_730020	K16886
gene_v1_660004	K04084
gene_v1_1770003	K00394
gene_v1_240017	K03798


> install.packages("KEGGexpressionmapper-0.3.tar.gz")
Installing package into ‘/home/hpc/pr74ma/ge34juq2/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package ‘KEGGexpressionMapper’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (KEGGexpressionMapper)
> library(KEGGexpressionMapper)
Loading required package: png
> KEGGexpressionMapper("Use_case_Sarah/DEG.tab","Use_case_Sarah/
Use_case_Sarah/DEG.tab         Use_case_Sarah/Expression.tab  Use_case_Sarah/KEGG.tab
> KEGGexpressionMapper("Use_case_Sarah/DEG.tab","Use_case_Sarah/KEGG.tab","Use_case_Sarah/Expression.tab")
[1] "We are integrating 9 KEGG orthologs"
[1] "We are integrating 9 KEGG-gene assignments"
[1] "We are analysing 13 KEGG pathways"
[1] "We are analysing 18 genes with expression"
>
